server:
    port: 8000

# logging:
#     level:
#         org:
#             springframework: DEBUG

spring:
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3306
        username: root
        password: 123456
    # sql:
    #     init: